### ISSUE TITLE
Problem with run meteor!

### ISSUE THREAD

**Issue by thearabbit** [mbrookes/formsy-mui-demo#4] opened 2016-02-24 10:21 UTC
```js
$ meteor                                                                
[[[[[ ~\D\meteor-app\formsy-mui-demo ]]]]]                              
                                                                        
=> Started proxy.                                                       
=> Started MongoDB.                                                     
npm-container: updating npm dependencies -- externalify,                
material-ui, formsy-react, formsy-material-ui, babelify...              
=> Errors prevented startup:                                            
                                                                        
   While building package npm-container:                                
   error: couldn't run `npm shrinkwrap`: Command failed: npm ERR!       
   Error: Problems were encountered                                     
   npm ERR! Please correct and try again.                               
   npm ERR! missing: react@^0.14.7, required by                         
   react-addons-transition-group@0.14.7                                 
   npm ERR! missing: react@^0.14.7, required by                         
   react-addons-update@0.14.7                                           
   npm ERR! missing: react@^0.14.7, required by                         
   react-addons-create-fragment@0.14.7                                  
   npm ERR! missing: react@^0.14.7, required by                         
   react-addons-pure-render-mixin@0.14.7                                
   npm ERR!     at shrinkwrap_                                          
   (C:\Users\Theara\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt
-os.windows.x86_32\dev_bundle\bin\node_modules\npm\lib\shrinkwrap.js:30:
15)                                                                     
```

**Comment by mbrookes** [comment] 2016-02-24 13:54
You might need to tweak the versions in package.json, I haven't updated this for a while.

**Comment by thearabbit** [comment] 2016-02-25 01:02
What the package should I change?
Please example.

**Comment by mbrookes** [comment] 2016-02-27 16:30
Dupe of #2? I have updated this in any case. Please try again with the current version.

**Closed by mbrookes** 2016-02-27 16:30 UTC

**Comment by thearabbit** [comment] 2016-02-28 03:07
Thanks, now it work fine.
Excuse me, I am an newbie with `NPM package`.
what the npm package `externalify, babelify`?

**Comment by mbrookes** [comment] 2016-02-28 10:30
http://lmgtfy.com/?q=externalify+browserify+meteor+npm

**Comment by thearabbit** [comment] 2016-02-28 13:53
Thanks.
